### ISSUE TITLE
[Feature Todo list] Trading System

### ISSUE THREAD

**Issue by BraedonWooding** [OrderOfThePorcupine/ProjectPorcupine#15]
<a href="https://github.com/sboigelot"><img src="https://avatars1.githubusercontent.com/u/6545998?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sboigelot](https://github.com/sboigelot)**
_Thursday Sep 01, 2016 at 11:05 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/TeamPorcupine/ProjectPorcupine/issues/1075_

----

Here is a list of task for the current simple trading system (rimworld like)

I'm adding it here as a reference to keep track of the progress in the feature. If you wish to handle one of the sub-tasks, don't hesitate to start on it, just post a comment here so we don't make concurrent work
- [x] Add landing pad furniture
- [x] make landing pad only buildable outside
- [x] Create a trader prototypes
- [x] The traders are random variation on trader prototypes
- [x] Add Currencies
- [x] Create a trade UI
- [x] Have trade ship landing on the landing pad and able to leave the map
- [x] Sell Items from stockpiles
- [x] Bougth items spawn near landing pad
- [x] Trade ship visit at random times (using Scheduler system [PR #1097])
- [x] Register TradeShip on the World (and have a trade Controller if needed) [PR #1097]
- [x] Remove Context Menu Item on Landing pad to "Call a trade ship" this is just a test action [PR #1097]
- [x] Disallow trade to be concluded if player/trader do not have enough money or stock [PR #1097]
- [x] Have a base price on item prototypes [PR #1109]
- [x] Have a category on item prototypes [PR #1109]
- [x] Allow trader prototype to have a stock prototype based on item category (keep the version based on item object type as well) [PR #1191]
- [ ] Make currencies visible somewhere on the UI [PR #1143]
- [ ] Trade ship visit frequency increase according to [base value]/[time played]/[renown]
- [ ] Make "trade with trader" a queuable job by selecting a character and context menu on a trade ship on a landing pad (remove auto opening of trading UI when trade ship land) (Waiting for new job system)
- [ ] Save / Load TradeShip currently visiting
- [ ] When the trade is complete, do not teleport item from stockpile to the trader ship, create hauling job for them. Only finish the trade when all item have been transported (PlanetBase style)
- [ ] Add a funiture (console, beacon, etc) that can increase the likelyhood of a trader visiting the base (call specific trader, call anyone, etc) at the cost of the time of a character
- [ ] Add a Banished-like feature that allow the player to request a specific item to a trader for him to bring on his next visit. The requested item will have a higher price

Later
- [ ] Use #1063 for trade ship visits

**Comment by BraedonWooding** [comment]
<a href="https://github.com/mikejbrown"><img src="https://avatars2.githubusercontent.com/u/855931?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mikejbrown](https://github.com/mikejbrown)**
_Thursday Sep 01, 2016 at 14:54 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

> Trade ship visit at random times (game event?)

This would be a perfect use case for the new Scheduler system #998 if/when that gets merged.

**Comment by BraedonWooding** [comment]
<a href="https://github.com/sboigelot"><img src="https://avatars1.githubusercontent.com/u/6545998?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sboigelot](https://github.com/sboigelot)**
_Thursday Sep 01, 2016 at 15:02 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

@mikejbrown I'll have a look at it as soon as I can if no-one else pick it up before ;)

**Comment by BraedonWooding** [comment]
<a href="https://github.com/buggy213"><img src="https://avatars1.githubusercontent.com/u/9620842?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [buggy213](https://github.com/buggy213)**
_Friday Sep 02, 2016 at 04:08 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Do you think it would be a good idea to have some way to convert between currencies?

**Comment by BraedonWooding** [comment]
<a href="https://github.com/TomMalbran"><img src="https://avatars2.githubusercontent.com/u/1299997?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TomMalbran](https://github.com/TomMalbran)**
_Friday Sep 02, 2016 at 04:24 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

A few other suggestions for later:
1. Since we have a ship that lands, I think that it will make a lot of sense that when the trade is complete, we would need to move the resources we sold into the ship. Make them instantly disappear from a stockpile feels unrealistic. The trader could come with some characters that could help move the items, and they will leave once all items are in the ship. Same can happen when unloading, we could define and unloading stockpile close to the landing pad and the items we bought would be move from the ship into the stockpile.
2. We could also add a console to call other traders if we need to. We can play here with how it may work, which other traders we could call and when? do we need to pay them extra to come? are they prices more expensive since we demand them?
3. What if we could request a trader to bring certain items (which ones depend on the trader type). The amount can be random, and even whether they always bring them too, but with a high probability of having them. This items would have a higher price.

**Comment by BraedonWooding** [comment]
<a href="https://github.com/buggy213"><img src="https://avatars1.githubusercontent.com/u/9620842?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [buggy213](https://github.com/buggy213)**
_Friday Sep 02, 2016 at 06:02 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

In response to the person above me
1. I agree, there should be a time element involved with trading.
2. One possible implementation is the RimWorld trading system, where traders stay in your general vicinity for some amount of time during which you can trade with them. An interesting mechanic would be trading persistence, where several traders would return time and time again. 
3. This is the way it works in Dwarf Fortress / Banished and it generally works pretty well in terms of actually getting things you want.

**Comment by BraedonWooding** [comment]
<a href="https://github.com/TomMalbran"><img src="https://avatars2.githubusercontent.com/u/1299997?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TomMalbran](https://github.com/TomMalbran)**
_Friday Sep 02, 2016 at 06:21 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

@buggy213 
1. I was thinking of how PlanetBase worked, where the ship lands, you do the trade and then the character load/unload the items. It works good there.
2. A RinWorld style will work fine. Maybe depending on the relation with the Faction some would first announce and request permission to land, and others could just land. You could also call factions you are in a good relationship with to do some trades, if they are relatively close.
3. Yes I was thinking on Banished when I suggested that.

**Comment by BraedonWooding** [comment]
<a href="https://github.com/sboigelot"><img src="https://avatars1.githubusercontent.com/u/6545998?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sboigelot](https://github.com/sboigelot)**
_Friday Sep 02, 2016 at 07:53 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

@buggy213 @TomMalbran Great set of suggestion! thanks, I updated the issue to add them. 

About

> Do you think it would be a good idea to have some way to convert between currencies?

I think this is more a question for #776

**Comment by BraedonWooding** [comment]
<a href="https://github.com/buggy213"><img src="https://avatars1.githubusercontent.com/u/9620842?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [buggy213](https://github.com/buggy213)**
_Monday Sep 05, 2016 at 02:12 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

I've created a simple label element for the currencies. #1143

**Comment by BraedonWooding** [comment]
<a href="https://github.com/buggy213"><img src="https://avatars1.githubusercontent.com/u/9620842?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [buggy213](https://github.com/buggy213)**
_Friday Sep 09, 2016 at 02:44 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

I've finished the request system in #1143, will proceed to work on adding trading console

**Comment by BraedonWooding** [comment]
<a href="https://github.com/Tranberry"><img src="https://avatars0.githubusercontent.com/u/16529?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tranberry](https://github.com/Tranberry)**
_Friday Sep 09, 2016 at 07:35 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

On the frequency of trader visits wouldn't it be more reasonable that the wares be better as base value/renown/time played increased, but then I have no clue how rare these visits would be in your implementation, or how frequent the visits will be at max.

**Comment by BraedonWooding** [comment]
<a href="https://github.com/sboigelot"><img src="https://avatars1.githubusercontent.com/u/6545998?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sboigelot](https://github.com/sboigelot)**
_Friday Sep 09, 2016 at 09:29 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

@Tranberry I think the balance of the trade system (frequency / quality of goods/ etc) will be for later and depend vastly on the world, a space station around a high traffic wormhole will see more trade ship then a far-edge-of-the-galaxy mining base

**Comment by BraedonWooding** [comment]
<a href="https://github.com/buggy213"><img src="https://avatars1.githubusercontent.com/u/9620842?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [buggy213](https://github.com/buggy213)**
_Saturday Sep 10, 2016 at 04:19 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

As of now I don't think it's even possible to modify existing events, you have to create a new one each time you want to change it

**Comment by BraedonWooding** [comment]
<a href="https://github.com/sboigelot"><img src="https://avatars1.githubusercontent.com/u/6545998?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sboigelot](https://github.com/sboigelot)**
_Saturday Sep 10, 2016 at 10:44 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

@buggy213 you can change the event property if you keep a c# reference to it, it should work. The TradeController keep a reference to the trade event.

**Comment by BraedonWooding** [comment]
<a href="https://github.com/mikejbrown"><img src="https://avatars2.githubusercontent.com/u/855931?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mikejbrown](https://github.com/mikejbrown)**
_Thursday Oct 06, 2016 at 05:33 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Any signs of life?

**Comment by BraedonWooding** [comment]
<a href="https://github.com/sboigelot"><img src="https://avatars1.githubusercontent.com/u/6545998?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sboigelot](https://github.com/sboigelot)**
_Thursday Oct 06, 2016 at 06:23 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Hey @mikejbrown, I'm super busy at work since 2 weeks (release sprint for our product) but I will come back to this soon

**Comment by BraedonWooding** [comment]
<a href="https://github.com/sboigelot"><img src="https://avatars1.githubusercontent.com/u/6545998?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sboigelot](https://github.com/sboigelot)**
_Monday Jan 09, 2017 at 20:51 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Well sorry everyone, we are 3 months later and I still didn't have time to come back; (it's been a mess at work, PO leaving and customer super un-happy) But I'm keeping a silent look on the project! Great work everyone, it's cool to see it still active.

I hope I can come back soon, but meanwhile, I'm happy to see some of you taking some of the features of this epic! Thanks a lot to all the contributors!
